### ISSUE TITLE
environment is not a legal parameter in an Ansible Playbook

### ISSUE THREAD

**Issue by mrkz** [albertomurillo/ansible-openstack#2]
Using Ansible 1.5.4 the usage of 

```
    # environment:
    #   http_proxy: http://proxy-server.example.com:8080
    #   no_proxy: localhost,127.0.0.1,.example.com
```

in `openstack.yml` as described in [previous commit](https://github.com/albertomurillo/ansible-openstack/blob/3a22d8725d13f64053f39ccf8b4be3572fd99ed9/openstack.yml#L21) is not supported.

**Comment by albertomurillo** [comment]
As described on https://github.com/albertomurillo/ansible-openstack/blob/master/roles/os-common/meta/main.yml#L10

The minimal ansible version is 2.1
